apiVersion: v1
kind: Pod
metadata:
  name: controller
  namespace: wasm-rust-simple
spec:
  serviceAccountName: custom-controller
  containers:
    - name: controller
      image: "wasm-operator-simple-rust:latest"
      #command: ["sh", "-c", "sleep 3600"]
      imagePullPolicy: IfNotPresent
      env:
        - name: RUST_LOG
          value: "debug"
        - name: PREDICTION_SERVER
          value: "{{REPLACE.PREDICTION_SERVER_URL}}"
      resources:
        requests:
          memory: "640Mi"
        limits:
          memory: "1280Mi"
      volumeMounts:
        - mountPath: "/wasm-source-pvc"
          name: wasm-source-pvc
        - mountPath: "/tmp/wasmop-cache"
          name: wasmop-cache-pvc
    - name: prediction-sidecar
      image: prediction_webserver:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
          protocol: TCP
  volumes:
    - name: wasm-source-pvc
      persistentVolumeClaim:
        claimName: wasm-source-pvc
    - name: wasmop-cache-pvc
      persistentVolumeClaim:
        claimName: wasmop-cache-pvc
