# PV and PVC to get the source code of the WasmOperator
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wasm-source-pv
  labels:
    usage: wasm-operator-source-code
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/host" # Path inside the kind cluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wasm-source-pvc
  namespace: wasm-rust-simple
spec:
  storageClassName: manual
  selector:
    matchLabels:
      usage: wasm-operator-source-code
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 512Mi
---
# PV and PVC to store the state of the WasmOperator
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wasmop-cache-pv
  labels:
    usage: wasmop-cache
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/host/cache" # Path inside the kind cluster, right now this maps to a directory on the host for testing purposes but this is not necessary
    #path: "/tmp/wasmop-cache" # Path inside the kind cluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wasmop-cache-pvc
  namespace: wasm-rust-simple
spec:
  storageClassName: manual
  selector:
    matchLabels:
      usage: wasmop-cache
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi