apiVersion: "test.dev/v1"
kind: WasmOperator
metadata:
  name: simple-rust-operator
  namespace: default
spec:
  wasm: ./simple_child_controller.wasm
  env:
    - name: RUST_LOG
      value: "info"
    - name: HEAP_MEM_SIZE
      value: "90000000"