apiVersion: v1
kind: Namespace
metadata:
  name: "wasm-rust0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: "wasm-rust1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: "wasm-rust2"
---
apiVersion: v1
kind: Namespace
metadata:
  name: "wasm-rust3"
---
apiVersion: v1
kind: Namespace
metadata:
  name: "wasm-rust4"
---

