name: wasm-rust0
wasm: ./ring-child-controller.wasm
env:
  - name: RUST_LOG
    value: "info"
  - name: IN_NAMESPACE
    value: "wasm-rust0"
  - name: OUT_NAMESPACE
    value: "wasm-rust1"
  - name: HEAP_MEM_SIZE
    value: "90000000"
---
name: wasm-rust1
wasm: ./ring-child-controller.wasm
env:
  - name: RUST_LOG
    value: "info"
  - name: IN_NAMESPACE
    value: "wasm-rust1"
  - name: OUT_NAMESPACE
    value: "wasm-rust2"
  - name: HEAP_MEM_SIZE
    value: "90000000"
---
name: wasm-rust2
wasm: ./ring-child-controller.wasm
env:
  - name: RUST_LOG
    value: "info"
  - name: IN_NAMESPACE
    value: "wasm-rust2"
  - name: OUT_NAMESPACE
    value: "wasm-rust3"
  - name: HEAP_MEM_SIZE
    value: "90000000"
---
name: wasm-rust3
wasm: ./ring-child-controller.wasm
env:
  - name: RUST_LOG
    value: "info"
  - name: IN_NAMESPACE
    value: "wasm-rust3"
  - name: OUT_NAMESPACE
    value: "wasm-rust4"
  - name: HEAP_MEM_SIZE
    value: "90000000"
---
name: wasm-rust4
wasm: ./ring-child-controller.wasm
env:
  - name: RUST_LOG
    value: "info"
  - name: IN_NAMESPACE
    value: "wasm-rust4"
  - name: OUT_NAMESPACE
    value: "wasm-rust0"
  - name: HEAP_MEM_SIZE
    value: "90000000"
---

