//! # Host API Module
//!
//! This module defines the host-side API for interactions with Wasm modules. It includes
//! the necessary bindings generated by `wasmtime::component::bindgen!` and implements
//! the host functions that Wasm modules can call, such as sending requests to the
//! Kubernetes API and handling asynchronous responses.
use anyhow::Result;
use k8s_openapi::api::core::v1::Pod;
use kube::api::{
    ApiResource as KubeApiResource, DeleteParams as KubeDeleteParams,
    EvictParams as KubeEvictParams, GetParams as KubeGetParams, ListParams as KubeListParams,
    LogParams as KubeLogParams, PatchParams as KubePatchParams, PostParams as KubePostParams,
};
use kube::core::{dynamic::DynamicObject, metadata::PartialObjectMeta};
use kube::Api;
use tracing::{debug, error};

use crate::host::helper::{get_dynamic_api, get_meta_api, to_kube_patch};
use crate::host::state::State;
use crate::host::watch_stream_handler::{WatchStreamHandler, WatchStreamSignature};
use crate::kubernetes::KubernetesService;

use crate::host::wit::bindings::local::kube::api::{
    ApiCategory, ApiResource, CreateParams, DeleteParams, Error, EvictParams, Host, JsonValue,
    ListParams, LogParams, PatchParams, PatchType, Scope, WatchId, WatchParams,
};

/// This provides the actual implementations of the host functions that can be called by the WasmOperators.
impl Host for State {
    /// Fetches a resource from the Kubernetes API.
    fn get_resource(
        &mut self,
        api: ApiResource,
        name: String,
        resource_version: Option<String>,
        scope: Scope,
    ) -> Result<JsonValue, Error> {
        let api_res = KubeApiResource::from(&api);
        let gp = KubeGetParams { resource_version };

        self.execute_host_function(|| async move {
            let k8s_client = KubernetesService::global_client().await?;

            let obj_str = match scope {
                Scope::Full => {
                    let kube_api =
                        get_dynamic_api(k8s_client.clone(), api.namespace.clone(), &api_res);
                    let obj = kube_api.get_with(&name, &gp).await?;
                    serde_json::to_string(&obj)?
                }
                Scope::MetadataOnly => {
                    let kube_api = get_meta_api(k8s_client.clone(), &api, &api_res);
                    let obj = kube_api.get_metadata_with(&name, &gp).await?;
                    serde_json::to_string(&obj)?
                }
                Scope::Subresource(sub) => {
                    let kube_api =
                        get_dynamic_api(k8s_client.clone(), api.namespace.clone(), &api_res);
                    let obj = kube_api.get_subresource(&sub, &name).await?;
                    serde_json::to_string(&obj)?
                }
            };

            Ok(obj_str)
        })
    }

    /// Lists resources from the Kubernetes API.
    fn list_resources(
        &mut self,
        api: ApiResource,
        params: ListParams,
        scope: Scope,
    ) -> Result<JsonValue, Error> {
        let api_res = KubeApiResource::from(&api);
        let lp = KubeListParams::from(params);

        self.execute_host_function(|| async move {
            let k8s_client = KubernetesService::global_client().await?;
            match scope {
                Scope::Full => {
                    let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
                    let list = kube_api.list(&lp).await?;
                    Ok(serde_json::to_string(&list)?)
                }
                Scope::MetadataOnly => {
                    let kube_api = get_meta_api(k8s_client, &api, &api_res);
                    let list = kube_api.list_metadata(&lp).await?;
                    Ok(serde_json::to_string(&list)?)
                }
                Scope::Subresource(_) => Err(Error::Other(
                    "List operation is not supported on subresources".to_string(),
                )),
            }
        })
    }

    /// Creates a new resource in the Kubernetes API.
    fn create_resource(
        &mut self,
        api: ApiResource,
        body: JsonValue,
        params: CreateParams,
    ) -> Result<JsonValue, Error> {
        let api_res = KubeApiResource::from(&api);
        let pp = KubePostParams::from(params);
        let data: DynamicObject = serde_json::from_str(&body)?;

        self.execute_host_function(|| async move {
            let k8s_client = KubernetesService::global_client().await?;

            let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
            let obj = kube_api.create(&pp, &data).await?;
            Ok(serde_json::to_string(&obj)?)
        })
    }

    /// Creates a subresource in the Kubernetes API.
    fn create_subresource(
        &mut self,
        api: ApiResource,
        main_resource: String,
        subresource: String,
        body: JsonValue,
        params: CreateParams,
    ) -> Result<JsonValue, Error> {
        let api_res = KubeApiResource::from(&api);
        let pp = KubePostParams::from(params);
        let data: serde_json::Value = serde_json::from_str(&body)?;

        self.execute_host_function(|| async move {
            let k8s_client = KubernetesService::global_client().await?;

            let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
            let obj: serde_json::Value = kube_api
                .create_subresource(&subresource, &main_resource, &pp, &data)
                .await?;
            Ok(serde_json::to_string(&obj)?)
        })
    }

    /// Deletes a resource from the Kubernetes API.
    fn delete_resource(
        &mut self,
        api: ApiResource,
        name: wasmtime::component::__internal::String,
        params: DeleteParams,
        scope: Scope,
    ) -> std::prelude::v1::Result<JsonValue, Error> {
        let api_res = KubeApiResource::from(&api);
        let dp = KubeDeleteParams::from(params);

        self.execute_host_function(|| async move {
            let k8s_client = KubernetesService::global_client().await?;

            match scope {
                Scope::Full | Scope::Subresource(_) => {
                    let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
                    let res = kube_api.delete(&name, &dp).await?;
                    let val = match res {
                        either::Either::Left(obj) => serde_json::to_value(&obj)?,
                        either::Either::Right(status) => serde_json::to_value(&status)?,
                    };
                    Ok(serde_json::to_string(&val)?)
                }
                Scope::MetadataOnly => {
                    let kube_api = get_meta_api(k8s_client, &api, &api_res);
                    let res = kube_api.delete(&name, &dp).await?;
                    let val = match res {
                        either::Either::Left(meta) => serde_json::to_value(&meta)?,
                        either::Either::Right(status) => serde_json::to_value(&status)?,
                    };
                    Ok(serde_json::to_string(&val)?)
                }
            }
        })
    }

    /// Deletes a collection of resources from the Kubernetes API.
    fn delete_collection(
        &mut self,
        api: ApiResource,
        delete_params: DeleteParams,
        list_params: ListParams,
        scope: Scope,
    ) -> std::prelude::v1::Result<JsonValue, Error> {
        let api_res = KubeApiResource::from(&api);
        let dp = KubeDeleteParams::from(delete_params);
        let lp = KubeListParams::from(list_params);

        self.execute_host_function(|| async move {
            let k8s_client = KubernetesService::global_client().await?;

            match scope {
                Scope::Full | Scope::Subresource(_) => {
                    let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
                    let res = kube_api.delete_collection(&dp, &lp).await?;
                    let val = match res {
                        either::Either::Left(list) => serde_json::to_value(&list)?,
                        either::Either::Right(status) => serde_json::to_value(&status)?,
                    };
                    Ok(serde_json::to_string(&val)?)
                }
                Scope::MetadataOnly => {
                    let kube_api = get_meta_api(k8s_client, &api, &api_res);
                    let res = kube_api.delete_collection(&dp, &lp).await?;
                    let val = match res {
                        either::Either::Left(list) => serde_json::to_value(&list)?,
                        either::Either::Right(status) => serde_json::to_value(&status)?,
                    };
                    Ok(serde_json::to_string(&val)?)
                }
            }
        })
    }

    /// Patches an existing resource in the Kubernetes API.
    fn patch_resource(
        &mut self,
        api: ApiResource,
        name: wasmtime::component::__internal::String,
        patch_type: PatchType,
        body: JsonValue,
        params: PatchParams,
        scope: Scope,
    ) -> std::prelude::v1::Result<JsonValue, Error> {
        let api_res = KubeApiResource::from(&api);
        let pp = KubePatchParams::from(params);
        let kube_patch = to_kube_patch(patch_type, body)?;

        self.execute_host_function(|| async move {
            let k8s_client = KubernetesService::global_client().await?;

            match scope {
                Scope::Full => {
                    let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
                    let obj = kube_api.patch(&name, &pp, &kube_patch).await?;
                    Ok(serde_json::to_string(&obj)?)
                }
                Scope::MetadataOnly => {
                    let kube_api = get_meta_api(k8s_client, &api, &api_res);
                    let obj = kube_api.patch_metadata(&name, &pp, &kube_patch).await?;
                    Ok(serde_json::to_string(&obj)?)
                }
                Scope::Subresource(sub) => {
                    let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
                    let obj = kube_api
                        .patch_subresource(&sub, &name, &pp, &kube_patch)
                        .await?;
                    Ok(serde_json::to_string(&obj)?)
                }
            }
        })
    }

    /// Replaces an existing resource in the Kubernetes API.
    fn replace_resource(
        &mut self,
        api: ApiResource,
        name: wasmtime::component::__internal::String,
        body: JsonValue,
        params: CreateParams,
        scope: Scope,
    ) -> std::prelude::v1::Result<JsonValue, Error> {
        let api_res = KubeApiResource::from(&api);
        let pp = KubePostParams::from(params);

        self.execute_host_function(|| async move {
            let k8s_client = KubernetesService::global_client().await?;

            match scope {
                Scope::Full => {
                    let data: DynamicObject = serde_json::from_str(&body)?;
                    let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
                    let obj = kube_api.replace(&name, &pp, &data).await?;
                    Ok(serde_json::to_string(&obj)?)
                }
                Scope::MetadataOnly => {
                    let data: PartialObjectMeta<DynamicObject> = serde_json::from_str(&body)?;
                    let kube_api = get_meta_api(k8s_client, &api, &api_res);
                    let obj = kube_api.replace(&name, &pp, &data).await?;
                    Ok(serde_json::to_string(&obj)?)
                }
                Scope::Subresource(sub) => {
                    let data: serde_json::Value = serde_json::from_str(&body)?;
                    let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
                    let obj = kube_api
                        .replace_subresource(&sub, &name, &pp, &data)
                        .await?;
                    Ok(serde_json::to_string(&obj)?)
                }
            }
        })
    }

    /// Subscribes to a watch stream for Kubernetes resources.
    fn subscribe_watch_stream(
        &mut self,
        api: ApiResource,
        version: String,
        params: WatchParams,
        scope: Scope,
    ) -> Result<WatchId, Error> {
        let operator = self.operator.clone();
        self.execute_host_function(|| async move {
            let watch_id = match scope {
                Scope::Full => {
                    debug!("Subscribing to watch stream for resource kind: {}, namespace: {:?}, for operator {}", api.kind, api.namespace, &operator.cr.name);
                    let accept_bookmarks = params.bookmark;
                    let ws = WatchStreamSignature::from((api, params));
                    let watch_id = WatchStreamHandler::get_instance()
                        .register_watch_stream(operator, ws, version, accept_bookmarks).await?;
                    watch_id
                }
                Scope::MetadataOnly => {
                    error!("Watch operation is currently not supported for metadata only, implement this in the future if needed");
                    return Err(Error::Other(
                        "Watch operation is currently not supported for metadata only".to_string(),
                    ));
                }
                Scope::Subresource(_) => {
                    return Err(Error::Other(
                        "Watch operation is not supported on subresources".to_string(),
                    ));
                }
            };

            Ok(watch_id)
        })
    }

    /// Retrieves logs from a Kubernetes Pod.
    fn get_logs_string(
        &mut self,
        api: ApiResource,
        name: String,
        params: LogParams,
    ) -> Result<String, Error> {
        let namespace = api.namespace.as_deref();
        let lp = KubeLogParams::from(params);

        self.execute_host_function(|| async move {
            let k8s_client = KubernetesService::global_client().await?;

            let kube_api = if let Some(ns) = namespace {
                Api::<Pod>::namespaced(k8s_client.clone(), ns)
            } else {
                Api::<Pod>::all(k8s_client.clone())
            };

            Ok(kube_api.logs(&name, &lp).await?)
        })
    }

    /// Evicts a pod using the Kubernetes Eviction API.
    fn evict_subresource(
        &mut self,
        api: ApiResource,
        name: String,
        params: EvictParams,
    ) -> Result<JsonValue, Error> {
        let namespace = api.namespace.as_deref();
        let ep = KubeEvictParams::from(params);

        self.execute_host_function(|| async move {
            let k8s_client = KubernetesService::global_client().await?;

            let kube_api = if let Some(ns) = namespace {
                Api::<Pod>::namespaced(k8s_client.clone(), ns)
            } else {
                Api::<Pod>::all(k8s_client.clone())
            };

            let status = kube_api.evict(&name, &ep).await?;
            Ok(serde_json::to_string(&status)?)
        })
    }

    /// Gets the version of the Kubernetes API server.
    fn get_api_server_version(&mut self) -> Result<String, Error> {
        self.execute_host_function(|| async move {
            let k8s_client = KubernetesService::global_client().await?;

            let info = k8s_client.apiserver_version().await?;
            Ok(serde_json::to_string(&info)?)
        })
    }

    /// Lists supported API versions from the Kubernetes cluster.
    fn list_api_version(
        &mut self,
        category: ApiCategory,
        aggregated: bool,
    ) -> Result<String, Error> {
        self.execute_host_function(|| async move {
            let k8s_client = KubernetesService::global_client().await?;

            match (category, aggregated) {
                (ApiCategory::Core, false) => {
                    let res = k8s_client.list_core_api_versions().await?;
                    Ok(serde_json::to_string(&res)?)
                }
                (ApiCategory::Core, true) => {
                    let res = k8s_client.list_core_api_versions_aggregated().await?;
                    Ok(serde_json::to_string(&res)?)
                }
                (ApiCategory::Named, false) => {
                    let res = k8s_client.list_api_groups().await?;
                    Ok(serde_json::to_string(&res)?)
                }
                (ApiCategory::Named, true) => {
                    let res = k8s_client.list_api_groups_aggregated().await?;
                    Ok(serde_json::to_string(&res)?)
                }
            }
        })
    }

    /// Lists API resources supported by the Kubernetes cluster.
    fn list_api_resources(
        &mut self,
        category: ApiCategory,
        version: String,
    ) -> Result<String, Error> {
        self.execute_host_function(|| async move {
            let k8s_client = KubernetesService::global_client().await?;

            match category {
                ApiCategory::Core => {
                    let res = k8s_client.list_core_api_resources(&version).await?;
                    Ok(serde_json::to_string(&res)?)
                }
                ApiCategory::Named => {
                    let res = k8s_client.list_api_group_resources(&version).await?;
                    Ok(serde_json::to_string(&res)?)
                }
            }
        })
    }

    /// Returns the default namespace configured for the client.
    fn get_default_namespace(&mut self) -> Result<String, Error> {
        self.execute_host_function(|| async move {
            let k8s_client = KubernetesService::global_client().await?;

            let ns = k8s_client.default_namespace();
            Ok(ns.to_string())
        })
    }
}
