//! # Host API Module
//!
//! This module defines the host-side API for interactions with Wasm modules. It includes
//! the necessary bindings generated by `wasmtime::component::bindgen!` and implements
//! the host functions that Wasm modules can call, such as sending requests to the
//! Kubernetes API and handling asynchronous responses.

use std::{
    pin::Pin,
    sync::atomic::{AtomicU32, Ordering},
};

use dashmap::DashMap;
use futures::{stream, Stream, StreamExt};
use http::version;
use kube::{
    api::{
        ApiResource as KubeApiResource, DeleteParams as KubeDeleteParams,
        EvictParams as KubeEvictParams, GetParams as KubeGetParams, ListParams as KubeListParams,
        LogParams as KubeLogParams, Patch as KubePatch, PatchParams as KubePatchParams,
        PostParams as KubePostParams, Preconditions as KubePreconditions,
        PropagationPolicy as KubePropagationPolicy, ValidationDirective as KubeValidationDirective,
        VersionMatch as KubeVersionMatch, WatchParams as KubeWatchParams,
    },
    core::{dynamic::DynamicObject, metadata::PartialObjectMeta, WatchEvent as KubeWatchEvent},
    Api, Client, ResourceExt,
};

use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};

use k8s_openapi::api::core::v1::Pod;

use serde::Serialize;
use tokio::{runtime::Handle, sync::mpsc};
use tracing::{debug, error, info, warn};
use wasmtime::component::{Accessor, HasSelf};
use wasmtime::component::{StreamProducer, StreamReader};

use crate::{
    host::state::State,
    kubernetes::KubernetesService,
    runtime::wasmoperator::{OperatorState, OperatorUid, WasmOperatorRuntime},
};
use anyhow::Result;

pub mod bindings {
    wasmtime::component::bindgen!({
        path: "../wit",
        world: "wasmoperator",
    });
}

use bindings::local::kube::api::{
    ApiCategory, ApiResource, CreateParams, DeleteParams, Error, EvictParams, Host, HostWithStore,
    HttpError, JsonValue, ListParams, LogParams, PatchParams, PatchType, Preconditions,
    PropagationPolicy, Scope, ValidationDirective, VersionMatch, WatchEvent, WatchId, WatchParams,
};

//impl Host for State {}

//impl HostWithStore<State> for HasSelf<State> {
impl Host for State {
    fn get_resource(
        &mut self,
        api: ApiResource,
        name: String,
        resource_version: Option<String>,
        scope: Scope,
    ) -> Result<JsonValue, Error> {
        let api_res = to_kube_api_resource(&api);
        let gp = KubeGetParams { resource_version };

        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let k8s_client = KubernetesService::global_client()
                    .await
                    .map_err(to_wit_error)?;

                let obj_str = match scope {
                    Scope::Full => {
                        let kube_api =
                            get_dynamic_api(k8s_client.clone(), api.namespace.clone(), &api_res);
                        let obj = kube_api.get_with(&name, &gp).await.map_err(to_wit_error)?;
                        serde_json::to_string(&obj).map_err(to_serde_error)?
                    }
                    Scope::MetadataOnly => {
                        let kube_api = get_meta_api(k8s_client.clone(), &api, &api_res);
                        let obj = kube_api
                            .get_metadata_with(&name, &gp)
                            .await
                            .map_err(to_wit_error)?;
                        serde_json::to_string(&obj).map_err(to_serde_error)?
                    }
                    Scope::Subresource(sub) => {
                        let kube_api =
                            get_dynamic_api(k8s_client.clone(), api.namespace.clone(), &api_res);
                        let obj = kube_api
                            .get_subresource(&sub, &name)
                            .await
                            .map_err(to_wit_error)?;
                        serde_json::to_string(&obj).map_err(to_serde_error)?
                    }
                };

                serde_json::from_str(&obj_str).map_err(to_serde_error)
            })
        })
    }

    fn list_resources(
        &mut self,
        api: ApiResource,
        params: ListParams,
        scope: Scope,
    ) -> Result<JsonValue, Error> {
        debug!(
            "[HOST] list_resources called for kind={:?}, namespace={:?}",
            api.kind, api.namespace
        );

        let api_res = to_kube_api_resource(&api);
        let lp = to_kube_list_params(params);

        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let k8s_client = KubernetesService::global_client()
                    .await
                    .map_err(to_wit_error)?;

                tracing::info!(
                    "[HOST] list_resources called for kind={:?}, namespace={:?}",
                    api.kind,
                    api.namespace
                );
                match scope {
                    Scope::Full => {
                        let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
                        tracing::info!("[HOST] executing list on Kubernetes API server...");
                        let list = kube_api.list(&lp).await.map_err(to_wit_error)?;
                        tracing::info!("[HOST] list returned {} items", list.items.len());
                        serde_json::to_string(&list).map_err(to_serde_error)
                    }
                    Scope::MetadataOnly => {
                        let kube_api = get_meta_api(k8s_client, &api, &api_res);
                        let list = kube_api.list_metadata(&lp).await.map_err(to_wit_error)?;
                        serde_json::to_string(&list).map_err(to_serde_error)
                    }
                    Scope::Subresource(_) => Err(Error::Other(
                        "List operation is not supported on subresources".to_string(),
                    )),
                }
            })
        })
    }

    fn create_resource(
        &mut self,
        api: ApiResource,
        body: JsonValue,
        params: CreateParams,
    ) -> Result<JsonValue, Error> {
        let api_res = to_kube_api_resource(&api);
        let pp = to_kube_post_params(params);
        let data: DynamicObject = serde_json::from_str(&body).map_err(to_serde_error)?;

        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let k8s_client = KubernetesService::global_client()
                    .await
                    .map_err(to_wit_error)?;

                let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
                let obj = kube_api.create(&pp, &data).await.map_err(to_wit_error)?;
                serde_json::to_string(&obj).map_err(to_serde_error)
            })
        })
    }

    fn create_subresource(
        &mut self,
        api: ApiResource,
        main_resource: String,
        subresource: String,
        body: JsonValue,
        params: CreateParams,
    ) -> Result<JsonValue, Error> {
        let api_res = to_kube_api_resource(&api);
        let pp = to_kube_post_params(params);
        let data: serde_json::Value = serde_json::from_str(&body).map_err(to_serde_error)?;

        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let k8s_client = KubernetesService::global_client()
                    .await
                    .map_err(to_wit_error)?;

                let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
                let obj: serde_json::Value = kube_api
                    .create_subresource(&subresource, &main_resource, &pp, &data)
                    .await
                    .map_err(to_wit_error)?;
                serde_json::to_string(&obj).map_err(to_serde_error)
            })
        })
    }

    fn delete_resource(
        &mut self,
        api: ApiResource,
        name: wasmtime::component::__internal::String,
        params: DeleteParams,
        scope: Scope,
    ) -> std::prelude::v1::Result<JsonValue, Error> {
        let api_res = to_kube_api_resource(&api);
        let dp = to_kube_delete_params(params);

        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let k8s_client = KubernetesService::global_client()
                    .await
                    .map_err(to_wit_error)?;

                match scope {
                    Scope::Full | Scope::Subresource(_) => {
                        let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
                        let res = kube_api.delete(&name, &dp).await.map_err(to_wit_error)?;
                        let val = match res {
                            either::Either::Left(obj) => {
                                serde_json::to_value(&obj).map_err(to_serde_error)?
                            }
                            either::Either::Right(status) => {
                                serde_json::to_value(&status).map_err(to_serde_error)?
                            }
                        };
                        serde_json::to_string(&val).map_err(to_serde_error)
                    }
                    Scope::MetadataOnly => {
                        let kube_api = get_meta_api(k8s_client, &api, &api_res);
                        let res = kube_api.delete(&name, &dp).await.map_err(to_wit_error)?;
                        let val = match res {
                            either::Either::Left(meta) => {
                                serde_json::to_value(&meta).map_err(to_serde_error)?
                            }
                            either::Either::Right(status) => {
                                serde_json::to_value(&status).map_err(to_serde_error)?
                            }
                        };
                        serde_json::to_string(&val).map_err(to_serde_error)
                    }
                }
            })
        })
    }

    fn delete_collection(
        &mut self,
        api: ApiResource,
        delete_params: DeleteParams,
        list_params: ListParams,
        scope: Scope,
    ) -> std::prelude::v1::Result<JsonValue, Error> {
        let api_res = to_kube_api_resource(&api);
        let dp = to_kube_delete_params(delete_params);
        let lp = to_kube_list_params(list_params);

        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let k8s_client = KubernetesService::global_client()
                    .await
                    .map_err(to_wit_error)?;

                match scope {
                    Scope::Full | Scope::Subresource(_) => {
                        let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
                        let res = kube_api
                            .delete_collection(&dp, &lp)
                            .await
                            .map_err(to_wit_error)?;
                        let val = match res {
                            either::Either::Left(list) => {
                                serde_json::to_value(&list).map_err(to_serde_error)?
                            }
                            either::Either::Right(status) => {
                                serde_json::to_value(&status).map_err(to_serde_error)?
                            }
                        };
                        serde_json::to_string(&val).map_err(to_serde_error)
                    }
                    Scope::MetadataOnly => {
                        let kube_api = get_meta_api(k8s_client, &api, &api_res);
                        let res = kube_api
                            .delete_collection(&dp, &lp)
                            .await
                            .map_err(to_wit_error)?;
                        let val = match res {
                            either::Either::Left(list) => {
                                serde_json::to_value(&list).map_err(to_serde_error)?
                            }
                            either::Either::Right(status) => {
                                serde_json::to_value(&status).map_err(to_serde_error)?
                            }
                        };
                        serde_json::to_string(&val).map_err(to_serde_error)
                    }
                }
            })
        })
    }

    fn patch_resource(
        &mut self,
        api: ApiResource,
        name: wasmtime::component::__internal::String,
        patch_type: PatchType,
        body: JsonValue,
        params: PatchParams,
        scope: Scope,
    ) -> std::prelude::v1::Result<JsonValue, Error> {
        let api_res = to_kube_api_resource(&api);
        let pp = to_kube_patch_params(params);
        let kube_patch = to_kube_patch(patch_type, body)?;

        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let k8s_client = KubernetesService::global_client()
                    .await
                    .map_err(to_wit_error)?;

                match scope {
                    Scope::Full => {
                        let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
                        let obj = kube_api
                            .patch(&name, &pp, &kube_patch)
                            .await
                            .map_err(to_wit_error)?;
                        serde_json::to_string(&obj).map_err(to_serde_error)
                    }
                    Scope::MetadataOnly => {
                        let kube_api = get_meta_api(k8s_client, &api, &api_res);
                        let obj = kube_api
                            .patch_metadata(&name, &pp, &kube_patch)
                            .await
                            .map_err(to_wit_error)?;
                        serde_json::to_string(&obj).map_err(to_serde_error)
                    }
                    Scope::Subresource(sub) => {
                        let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
                        let obj = kube_api
                            .patch_subresource(&sub, &name, &pp, &kube_patch)
                            .await
                            .map_err(to_wit_error)?;
                        serde_json::to_string(&obj).map_err(to_serde_error)
                    }
                }
            })
        })
    }

    fn replace_resource(
        &mut self,
        api: ApiResource,
        name: wasmtime::component::__internal::String,
        body: JsonValue,
        params: CreateParams,
        scope: Scope,
    ) -> std::prelude::v1::Result<JsonValue, Error> {
        let api_res = to_kube_api_resource(&api);
        let pp = to_kube_post_params(params);

        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let k8s_client = KubernetesService::global_client()
                    .await
                    .map_err(to_wit_error)?;

                match scope {
                    Scope::Full => {
                        let data: DynamicObject =
                            serde_json::from_str(&body).map_err(to_serde_error)?;
                        let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
                        let obj = kube_api
                            .replace(&name, &pp, &data)
                            .await
                            .map_err(to_wit_error)?;
                        serde_json::to_string(&obj).map_err(to_serde_error)
                    }
                    Scope::MetadataOnly => {
                        let data: PartialObjectMeta<DynamicObject> =
                            serde_json::from_str(&body).map_err(to_serde_error)?;
                        let kube_api = get_meta_api(k8s_client, &api, &api_res);
                        let obj = kube_api
                            .replace(&name, &pp, &data)
                            .await
                            .map_err(to_wit_error)?;
                        serde_json::to_string(&obj).map_err(to_serde_error)
                    }
                    Scope::Subresource(sub) => {
                        let data: serde_json::Value =
                            serde_json::from_str(&body).map_err(to_serde_error)?;
                        let kube_api = get_dynamic_api(k8s_client, api.namespace.clone(), &api_res);
                        let obj = kube_api
                            .replace_subresource(&sub, &name, &pp, &data)
                            .await
                            .map_err(to_wit_error)?;
                        serde_json::to_string(&obj).map_err(to_serde_error)
                    }
                }
            })
        })
    }

    fn subscribe_watch_stream(
        &mut self,
        api: ApiResource,
        version: String,
        params: WatchParams,
        scope: Scope,
    ) -> Result<WatchId, Error> {
        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let watch_id = match scope {
                    Scope::Full => {
                        debug!("Subscribing to watch stream for resource kind: {}, namespace: {:?}, for operator {}", api.kind, api.namespace, &self.operator.cr.name);
                        let ws = WatchStreamSignature::from((api, version, params));
                        let watch_id = WatchStreamHandler::get_instance()
                            .register_watch_stream(self.operator.clone(), ws).await?;
                        watch_id
                    }
                    Scope::MetadataOnly => {
                        error!("Watch operation is currently not supported for metadata only, implement this in the future if needed");
                        return Err(Error::Other(
                            "Watch operation is currently not supported for metadata only".to_string(),
                        ));
                    }
                    Scope::Subresource(_) => {
                        return Err(Error::Other(
                            "Watch operation is not supported on subresources".to_string(),
                        ));
                    }
                };

                Ok(watch_id)
            })
        })
    }

    // fn watch_resource(
    //     accessor: &Accessor<State, Self>,
    //     api: ApiResource,
    //     version: String,
    //     params: WatchParams,
    //     scope: Scope,
    // ) -> Result<StreamReader<Result<WatchEvent, Error>>, Error> {
    //     let api_res = to_kube_api_resource(&api);
    //     let wp = to_kube_watch_params(params);

    //     tokio::task::block_in_place(|| {
    //         tokio::runtime::Handle::current().block_on(async move {
    //             let k8s_client = KubernetesService::global_client()
    //         .await
    //         .map_err(to_wit_error)?;

    //     let kube_stream: std::pin::Pin<Box<dyn Stream<Item = Result<WatchEvent, Error>> + Send>> =
    //         match scope {
    //             Scope::Full => {
    //                 let kube_api = get_dynamic_api(k8s_client.clone(), &api, &api_res);
    //                 let stream = kube_api.watch(&wp, &version).await.map_err(to_wit_error)?;
    //                 transform_watch_stream(stream).boxed()
    //             }
    //             Scope::MetadataOnly => {
    //                 let kube_api = get_meta_api(k8s_client.clone(), &api, &api_res);
    //                 let stream = kube_api
    //                     .watch_metadata(&wp, &version)
    //                     .await
    //                     .map_err(to_wit_error)?;
    //                 transform_watch_stream(stream).boxed()
    //             }
    //             Scope::Subresource(_) => {
    //                 return Err(Error::Other(
    //                     "Watch operation is not supported on subresources".to_string(),
    //                 ));
    //             }
    //         };

    //     let (tx, rx) = mpsc::channel::<Result<WatchEvent, Error>>(32);
    //     let stream_reader = accessor
    //         .with(|mut access| StreamReader::new(&mut access, HostWatchStreamProducer::new(rx)))
    //         .map_err(|e| Error::Other(e.to_string()))?;

    //     accessor.spawn(WatchTask { kube_stream, tx });

    //     Ok(stream_reader)
    // })
    //     })
    // }

    fn get_logs_string(
        &mut self,
        api: ApiResource,
        name: String,
        params: LogParams,
    ) -> Result<String, Error> {
        let namespace = api.namespace.as_deref();
        let lp = to_kube_log_params(params);

        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let k8s_client = KubernetesService::global_client()
                    .await
                    .map_err(to_wit_error)?;

                let kube_api = if let Some(ns) = namespace {
                    Api::<Pod>::namespaced(k8s_client.clone(), ns)
                } else {
                    Api::<Pod>::all(k8s_client.clone())
                };

                kube_api.logs(&name, &lp).await.map_err(to_wit_error)
            })
        })
    }

    fn evict_subresource(
        &mut self,
        api: ApiResource,
        name: String,
        params: EvictParams,
    ) -> Result<JsonValue, Error> {
        let namespace = api.namespace.as_deref();
        let ep = to_kube_evict_params(params);

        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let k8s_client = KubernetesService::global_client()
                    .await
                    .map_err(to_wit_error)?;

                let kube_api = if let Some(ns) = namespace {
                    Api::<Pod>::namespaced(k8s_client.clone(), ns)
                } else {
                    Api::<Pod>::all(k8s_client.clone())
                };

                let status = kube_api.evict(&name, &ep).await.map_err(to_wit_error)?;
                serde_json::to_string(&status).map_err(to_serde_error)
            })
        })
    }

    fn get_api_server_version(&mut self) -> Result<String, Error> {
        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let k8s_client = KubernetesService::global_client()
                    .await
                    .map_err(to_wit_error)?;

                let info = k8s_client.apiserver_version().await.map_err(to_wit_error)?;
                serde_json::to_string(&info).map_err(to_serde_error)
            })
        })
    }

    fn list_api_version(
        &mut self,
        category: ApiCategory,
        aggregated: bool,
    ) -> Result<String, Error> {
        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let k8s_client = KubernetesService::global_client()
                    .await
                    .map_err(to_wit_error)?;

                match (category, aggregated) {
                    (ApiCategory::Core, false) => {
                        let res = k8s_client
                            .list_core_api_versions()
                            .await
                            .map_err(to_wit_error)?;
                        serde_json::to_string(&res).map_err(to_serde_error)
                    }
                    (ApiCategory::Core, true) => {
                        let res = k8s_client
                            .list_core_api_versions_aggregated()
                            .await
                            .map_err(to_wit_error)?;
                        serde_json::to_string(&res).map_err(to_serde_error)
                    }
                    (ApiCategory::Named, false) => {
                        let res = k8s_client.list_api_groups().await.map_err(to_wit_error)?;
                        serde_json::to_string(&res).map_err(to_serde_error)
                    }
                    (ApiCategory::Named, true) => {
                        let res = k8s_client
                            .list_api_groups_aggregated()
                            .await
                            .map_err(to_wit_error)?;
                        serde_json::to_string(&res).map_err(to_serde_error)
                    }
                }
            })
        })
    }

    fn list_api_resources(
        &mut self,
        category: ApiCategory,
        version: String,
    ) -> Result<String, Error> {
        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let k8s_client = KubernetesService::global_client()
                    .await
                    .map_err(to_wit_error)?;

                match category {
                    ApiCategory::Core => {
                        let res = k8s_client
                            .list_core_api_resources(&version)
                            .await
                            .map_err(to_wit_error)?;
                        serde_json::to_string(&res).map_err(to_serde_error)
                    }
                    ApiCategory::Named => {
                        let res = k8s_client
                            .list_api_group_resources(&version)
                            .await
                            .map_err(to_wit_error)?;
                        serde_json::to_string(&res).map_err(to_serde_error)
                    }
                }
            })
        })
    }

    fn get_default_namespace(&mut self) -> Result<String, Error> {
        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let k8s_client = KubernetesService::global_client()
                    .await
                    .map_err(to_wit_error)?;

                let ns = k8s_client.default_namespace();
                Ok(ns.to_string())
            })
        })
    }
}

// // ==========================================
// // Mappings & Helper Functions
// // ==========================================

fn to_kube_api_resource(api: &ApiResource) -> KubeApiResource {
    let api_version = if api.group.is_empty() {
        api.version.clone()
    } else {
        format!("{}/{}", api.group, api.version)
    };
    KubeApiResource {
        group: api.group.clone(),
        version: api.version.clone(),
        api_version,
        kind: api.kind.clone(),
        plural: api.plural.clone(),
    }
}

fn get_dynamic_api(
    client: Client,
    namespace: Option<String>,
    api_res: &KubeApiResource,
) -> Api<DynamicObject> {
    if let Some(ns) = namespace {
        Api::namespaced_with(client.clone(), &ns, api_res)
    } else {
        Api::all_with(client.clone(), api_res)
    }
}

fn get_meta_api(
    client: Client,
    api: &ApiResource,
    api_res: &KubeApiResource,
) -> Api<PartialObjectMeta<DynamicObject>> {
    if let Some(ns) = &api.namespace {
        Api::namespaced_with(client.clone(), ns, api_res)
    } else {
        Api::all_with(client.clone(), api_res)
    }
}

fn to_kube_propagation_policy(policy: PropagationPolicy) -> KubePropagationPolicy {
    match policy {
        PropagationPolicy::Orphan => KubePropagationPolicy::Orphan,
        PropagationPolicy::Background => KubePropagationPolicy::Background,
        PropagationPolicy::Foreground => KubePropagationPolicy::Foreground,
    }
}

fn to_kube_preconditions(p: Preconditions) -> KubePreconditions {
    KubePreconditions {
        uid: p.uid,
        resource_version: p.resource_version,
    }
}

fn to_kube_delete_params(dp: DeleteParams) -> KubeDeleteParams {
    KubeDeleteParams {
        dry_run: dp.dry_run,
        grace_period_seconds: dp.grace_period_seconds,
        propagation_policy: dp.propagation_policy.map(to_kube_propagation_policy),
        preconditions: dp.preconditions.map(to_kube_preconditions),
    }
}

fn to_kube_version_match(vm: VersionMatch) -> KubeVersionMatch {
    match vm {
        VersionMatch::Exact => KubeVersionMatch::Exact,
        VersionMatch::NotLater => KubeVersionMatch::NotOlderThan,
    }
}

fn to_kube_list_params(lp: ListParams) -> KubeListParams {
    KubeListParams {
        label_selector: lp.label_selector,
        field_selector: lp.field_selector,
        timeout: lp.timeout,
        limit: lp.limit,
        continue_token: lp.continue_token,
        version_match: lp.version_match.map(to_kube_version_match),
        resource_version: lp.resource_version,
    }
}

fn to_kube_post_params(pp: CreateParams) -> KubePostParams {
    KubePostParams {
        dry_run: pp.dry_run,
        field_manager: pp.field_manager,
    }
}

fn to_kube_validation_directive(vd: ValidationDirective) -> KubeValidationDirective {
    match vd {
        ValidationDirective::Strict => KubeValidationDirective::Strict,
        ValidationDirective::Warn => KubeValidationDirective::Warn,
        ValidationDirective::Ignore => KubeValidationDirective::Ignore,
    }
}

fn to_kube_patch_params(pp: PatchParams) -> KubePatchParams {
    KubePatchParams {
        dry_run: pp.dry_run,
        force: pp.force,
        field_manager: pp.field_manager,
        field_validation: pp.field_validation.map(to_kube_validation_directive),
    }
}

fn to_kube_patch(
    patch_type: PatchType,
    body: JsonValue,
) -> Result<KubePatch<serde_json::Value>, Error> {
    let parsed_value: serde_json::Value = serde_json::from_str(&body).map_err(to_serde_error)?;

    let patch = match patch_type {
        PatchType::Apply => KubePatch::Apply(parsed_value),
        PatchType::Merge => KubePatch::Merge(parsed_value),
        PatchType::Strategic => KubePatch::Strategic(parsed_value),
        PatchType::Json => {
            let patch_vec = serde_json::from_value(parsed_value).map_err(to_serde_error)?;
            KubePatch::Json(patch_vec)
        }
    };

    Ok(patch)
}

fn to_kube_watch_params(wp: WatchParams) -> KubeWatchParams {
    KubeWatchParams {
        label_selector: wp.label_selector,
        field_selector: wp.field_selector,
        timeout: wp.timeout,
        bookmarks: wp.bookmark,
        send_initial_events: wp.send_initial_events,
    }
}

fn to_kube_log_params(lp: LogParams) -> KubeLogParams {
    KubeLogParams {
        container: lp.container,
        follow: lp.follow,
        limit_bytes: lp.limit_bytes.map(|x| x as i64),
        pretty: lp.pretty,
        previous: lp.previous,
        since_seconds: lp.since_seconds.map(|x| x as i64),
        since_time: lp.since_time.and_then(|t| t.parse().ok()),
        tail_lines: lp.tail_lines.map(|x| x as i64),
        timestamps: lp.timestamps,
    }
}

fn to_kube_evict_params(ep: EvictParams) -> KubeEvictParams {
    KubeEvictParams {
        delete_options: ep.delete_options.map(to_kube_delete_params),
        post_options: to_kube_post_params(ep.post_options),
    }
}

fn to_wit_error<E>(err: E) -> Error
where
    E: Into<anyhow::Error>,
{
    let anyhow_err: anyhow::Error = err.into();

    if let Some(kube_err) = anyhow_err.downcast_ref::<kube::Error>() {
        match kube_err {
            kube::Error::Api(status) => {
                if status.code == 404 {
                    return Error::NotFound;
                }
                return Error::Http(HttpError {
                    code: status.code,
                    reason: status.reason.clone(),
                    message: status.message.clone(),
                });
            }
            _ => {}
        }
    }

    Error::Other(anyhow_err.to_string())
}

fn to_serde_error(err: serde_json::Error) -> Error {
    Error::Other(err.to_string())
}

use kube::Error as KubeError;
use std::sync::{Arc, LazyLock};
use tokio_stream::StreamMap;

type WatcherResult = Result<KubeWatchEvent<DynamicObject>, KubeError>;
type BoxedWatchStream = Pin<Box<dyn Stream<Item = Option<WatcherResult>> + Send>>;

enum StreamManagerCmd {
    Register {
        signature: WatchStreamSignature,
        operator: Arc<WasmOperatorRuntime>,
        stream: BoxedWatchStream,
    },
}

struct WatchStreamHandler {
    cmd_tx: mpsc::UnboundedSender<StreamManagerCmd>,
    next_id: AtomicU32,
}

#[derive(Clone, Debug)]
pub struct WatchStreamSignature {
    group: String,
    api_version: String,
    kind: String,
    plural: String,
    namespace: Option<String>,
    cluster_version: String,
    label_selector: Option<String>,
    field_selector: Option<String>,
    send_initial_events: bool,
    timeout: Option<u32>, // Remove as option
    bookmark: bool,       // Filter internally
    hash: u64,            // Precomputed internal hash
}

impl WatchStreamSignature {
    /// Returns the precomputed hash in O(1) time.
    #[inline]
    pub fn get_hash(&self) -> u64 {
        self.hash
    }
}

impl Hash for WatchStreamSignature {
    fn hash<H: Hasher>(&self, state: &mut H) {
        state.write_u64(self.hash);
    }
}

impl PartialEq for WatchStreamSignature {
    fn eq(&self, other: &Self) -> bool {
        // Fast-path comparison using precomputed hash before comparing full fields
        self.hash == other.hash
            && self.group == other.group
            && self.api_version == other.api_version
            && self.kind == other.kind
            && self.plural == other.plural
            && self.namespace == other.namespace
            && self.cluster_version == other.cluster_version
            && self.label_selector == other.label_selector
            && self.field_selector == other.field_selector
            && self.send_initial_events == other.send_initial_events
            && self.timeout == other.timeout
            && self.bookmark == other.bookmark
    }
}

impl Eq for WatchStreamSignature {}

impl From<(ApiResource, String, WatchParams)> for WatchStreamSignature {
    fn from((api, cluster_version, params): (ApiResource, String, WatchParams)) -> Self {
        let group = api.group;
        let api_version = api.version;
        let kind = api.kind;
        let plural = api.plural;
        let namespace = api.namespace;
        let label_selector = params.label_selector;
        let field_selector = params.field_selector;
        let send_initial_events = params.send_initial_events;
        let timeout = params.timeout;
        let bookmark = params.bookmark;

        // Calculate internal hash once during construction
        // Note: `timeout` and `bookmark` are omitted from signature calculation
        let mut hasher = DefaultHasher::new();
        group.hash(&mut hasher);
        api_version.hash(&mut hasher);
        kind.hash(&mut hasher);
        plural.hash(&mut hasher);
        namespace.hash(&mut hasher);
        cluster_version.hash(&mut hasher);
        label_selector.hash(&mut hasher);
        field_selector.hash(&mut hasher);
        send_initial_events.hash(&mut hasher);
        timeout.hash(&mut hasher);
        bookmark.hash(&mut hasher);
        let hash = hasher.finish();

        WatchStreamSignature {
            group,
            api_version,
            kind,
            plural,
            namespace,
            cluster_version,
            label_selector,
            field_selector,
            send_initial_events,
            timeout,
            bookmark,
            hash,
        }
    }
}

impl From<&WatchStreamSignature> for KubeApiResource {
    fn from(sig: &WatchStreamSignature) -> Self {
        let api_version = if sig.group.is_empty() {
            sig.api_version.clone()
        } else {
            format!("{}/{}", sig.group, sig.api_version)
        };
        KubeApiResource {
            group: sig.group.clone(),
            version: sig.api_version.clone(),
            api_version,
            kind: sig.kind.clone(),
            plural: sig.plural.clone(),
        }
    }
}

impl From<&WatchStreamSignature> for KubeWatchParams {
    fn from(sig: &WatchStreamSignature) -> Self {
        KubeWatchParams {
            label_selector: sig.label_selector.clone(),
            field_selector: sig.field_selector.clone(),
            timeout: sig.timeout,
            bookmarks: sig.bookmark,
            send_initial_events: sig.send_initial_events,
        }
    }
}

// TODO: let this loop react to SIGINT and SIGTERM signals to gracefully shutdown the stream handler and all associated streams.

// One global stream handler, this reduces overhead in comparrison to spawning a new task for each operator.
// This also creates an artificial bottleneck which is not bad because not all operators will be trying at the same time if watch events arive at the same time.
static WATCH_STREAM_HANDLER: LazyLock<Arc<WatchStreamHandler>> = LazyLock::new(|| {
    let (cmd_tx, mut cmd_rx) = mpsc::unbounded_channel::<StreamManagerCmd>();

    // Spawn the background worker that listens to all registered streams
    tokio::spawn(async move {
        let mut streams = StreamMap::new();
        let operators = DashMap::<WatchId, Arc<WasmOperatorRuntime>>::new();
        let cluster_resource_versions = DashMap::<WatchId, String>::new();

        loop {
            tokio::select! {
                // Handle new registrations
                cmd = cmd_rx.recv() => {
                    match cmd {
                        Some(StreamManagerCmd::Register { signature, operator, stream }) => {
                            operators.insert(signature.get_hash(), operator);
                            streams.insert(signature, stream);
                        }
                        None => {
                            // Command channel was closed (WatchStreamHandler was dropped)
                            warn!("Command channel closed for watch stream handler. Shutting down worker.");
                            break;
                        }
                    }
                }

                // Handle next event from any registered stream
                Some((id, stream_event)) = streams.next(), if !streams.is_empty() => {
                    let operator = operators.get(&id.get_hash()).expect("Operator should exist for registered stream");

                    warn!("Received event from stream {}: {:?}", id.get_hash(), stream_event);

                    match stream_event {
                        Some(event) => {
                            let process_obj = |obj: &DynamicObject, constructor: fn(String) -> WatchEvent| {
                                cluster_resource_versions.insert(id.get_hash(), obj.resource_version().unwrap_or_default());
                                match serde_json::to_string(obj) {
                                    Ok(json) => constructor(json),
                                    Err(e) => WatchEvent::Error(Error::Other(e.to_string())),
                                }
                            };

                            let watch_event: WatchEvent = match event {
                                Ok(KubeWatchEvent::Added(obj)) => process_obj(&obj, WatchEvent::Added),
                                Ok(KubeWatchEvent::Modified(obj)) => process_obj(&obj, WatchEvent::Modified),
                                Ok(KubeWatchEvent::Deleted(obj)) => process_obj(&obj, WatchEvent::Deleted),

                                Ok(KubeWatchEvent::Bookmark(bookmark)) => {
                                    cluster_resource_versions.insert(id.get_hash(), bookmark.metadata.resource_version.clone());
                                    serde_json::to_string(&bookmark)
                                        .map(WatchEvent::Bookmark)
                                        .unwrap_or_else(|e| WatchEvent::Error(Error::Other(format!("Bookmark serialization error: {e}"))))
                                }

                                Ok(KubeWatchEvent::Error(status)) => WatchEvent::Error(Error::Http(HttpError {
                                    code: status.code,
                                    reason: status.reason,
                                    message: status.message,
                                })),

                                // Handle a stream transport error
                                Err(e) => WatchEvent::Error(Error::Other(format!("Kubernetes watch stream error: {e}"))),
                            };

                            warn!("Currently {} streams are being watched", streams.len());
                            warn!("The current operator has {} registered streams", operators.len());
                            if let Err(e) = operator.cmd_tx.send(crate::runtime::wasmoperator::WORCommand::ProcessWatchEvent(id.get_hash(), watch_event)) {
                                tracing::warn!("Failed to queue watch event for stream {}: {:?}", id.get_hash(), e);
                            }
                        }
                        None => {
                            // Stream hit EOF (closed). Attempt to recreate the stream.
                            warn!("Stream {} closed (EOF). Cleaning up.", id.get_hash());
                            match WatchStreamHandler::get_watch_stream_from_signature(&id).await {
                                Ok(stream) => {streams.insert(id.clone(), stream);},
                                Err(e) => {
                                    warn!("Failed to recreate watch stream for signature {:?}: {}", id.get_hash(), e);
                                    operators.remove(&id.get_hash());
                                }
                            }
                        }
                    }
                }
            }
        }
    });

    Arc::new(WatchStreamHandler {
        cmd_tx,
        next_id: AtomicU32::new(1),
    })
});

impl WatchStreamHandler {
    fn get_instance() -> Arc<Self> {
        WATCH_STREAM_HANDLER.clone()
    }

    async fn get_watch_stream_from_signature(
        signature: &WatchStreamSignature,
    ) -> Result<BoxedWatchStream, Error> {
        let api_res = KubeApiResource::from(signature);
        let wp = KubeWatchParams::from(signature);

        let k8s_client = KubernetesService::global_client()
            .await
            .map_err(to_wit_error)?;
        let kube_api = get_dynamic_api(k8s_client, signature.namespace.clone(), &api_res);
        let stream = kube_api
            .watch(&wp, &signature.cluster_version)
            .await
            .map_err(to_wit_error)?;

        let stream_with_eof = stream
            .map(Some) // Wrap each event in Some to indicate it's a valid event
            .chain(futures::stream::once(async { None })); // Indicate the end of the stream with None

        Ok(Box::pin(stream_with_eof))
    }

    async fn register_watch_stream(
        &self,
        operator: Arc<WasmOperatorRuntime>,
        signature: WatchStreamSignature,
    ) -> Result<WatchId, Error> {
        let stream = WatchStreamHandler::get_watch_stream_from_signature(&signature).await?;

        //let id = self.next_id.fetch_add(1, Ordering::SeqCst);

        let cmd = StreamManagerCmd::Register {
            signature: signature.clone(),
            operator,
            stream,
        };
        self.cmd_tx
            .send(cmd)
            .map_err(|e| Error::Other(format!("Failed to send register command: {}", e)))?;

        Ok(signature.get_hash())
    }
}

// fn transform_watch_stream<T: Serialize>(
//     stream: impl Stream<Item = Result<KubeWatchEvent<T>, kube::Error>>,
// ) -> impl Stream<Item = Result<WatchEvent, Error>> {
//     stream.map(|event| {
//         let watch_event = event.map_err(to_wit_error)?;

//         let stringify = |obj: &T| serde_json::to_string(obj).map_err(to_wit_error);

//         match watch_event {
//             KubeWatchEvent::Added(obj) => {
//                 let s = stringify(&obj)?;
//                 Ok(WatchEvent::Added(s))
//             }
//             KubeWatchEvent::Modified(obj) => {
//                 let s = stringify(&obj)?;
//                 Ok(WatchEvent::Modified(s))
//             }
//             KubeWatchEvent::Deleted(obj) => {
//                 let s = stringify(&obj)?;
//                 Ok(WatchEvent::Deleted(s))
//             }
//             KubeWatchEvent::Bookmark(bookmark) => {
//                 let s = serde_json::to_string(&bookmark)
//                     .map_err(|e| todo!("Convert bookmark serialization error to Error: {:?}", e))?;
//                 Ok(WatchEvent::Bookmark(s))
//             }
//             KubeWatchEvent::Error(status) => {
//                 // The original function loses the original structure of `Error`
//                 // by formatting it into a string inside the Status object.
//                 // You will need to reconstruct a fallback `Error` here.
//                 let wit_error = Error::Other(format!("Kubernetes API error: {}", status.message));
//                 Ok(WatchEvent::Error(wit_error))
//             }
//         }
//     })
// }

// use std::task::{Context, Poll};
// use wasmtime::component::{Destination, StreamResult};
// use wasmtime::StoreContextMut;

// type WatchStreamItem = std::result::Result<WatchEvent, Error>;

// pub struct HostWatchStreamProducer {
//     pub rx: mpsc::Receiver<WatchStreamItem>,
// }

// impl HostWatchStreamProducer {
//     pub fn new(rx: mpsc::Receiver<WatchStreamItem>) -> Self {
//         Self { rx }
//     }
// }

// impl<State> StreamProducer<State> for HostWatchStreamProducer {
//     type Item = WatchStreamItem;
//     type Buffer = wasmtime::component::VecBuffer<Self::Item>;

//     fn poll_produce<'a>(
//         self: Pin<&mut Self>,
//         cx: &mut Context<'_>,
//         mut store: StoreContextMut<'a, State>,
//         mut dst: Destination<'a, Self::Item, Self::Buffer>,
//         finish: bool,
//     ) -> Poll<wasmtime::Result<StreamResult>> {
//         if finish {
//             return Poll::Ready(Ok(StreamResult::Cancelled));
//         }

//         let capacity = dst.remaining(&mut store).unwrap_or(16);
//         if capacity == 0 {
//             return Poll::Ready(Ok(StreamResult::Completed));
//         }
//         let this = self.get_mut();

//         let mut buffer = Vec::new();
//         let mut produced = 0;

//         while produced < capacity {
//             match this.rx.poll_recv(cx) {
//                 Poll::Ready(Some(item)) => {
//                     buffer.push(item);
//                     produced += 1;
//                 }
//                 Poll::Ready(None) => {
//                     if produced > 0 {
//                         dst.set_buffer(buffer.into());
//                     }
//                     return Poll::Ready(Ok(StreamResult::Dropped));
//                 }
//                 Poll::Pending => {
//                     break;
//                 }
//             }
//         }

//         if produced > 0 {
//             // We successfully pulled items; hand the populated buffer back to the guest
//             dst.set_buffer(buffer.into());
//             Poll::Ready(Ok(StreamResult::Completed))
//         } else {
//             // No items available right now, channel is pending
//             Poll::Pending
//         }
//     }
// }

// use wasmtime::component::AccessorTask;

// struct WatchTask {
//     kube_stream: std::pin::Pin<Box<dyn Stream<Item = Result<WatchEvent, Error>> + Send>>,
//     tx: mpsc::Sender<Result<WatchEvent, Error>>,
// }

// impl<D> AccessorTask<State, D> for WatchTask
// where
//     D: wasmtime::component::HasData + ?Sized,
// {
//     async fn run(mut self, _accessor: &Accessor<State, D>) -> wasmtime::Result<()> {
//         while let Some(event) = self.kube_stream.next().await {
//             if self.tx.send(event).await.is_err() {
//                 break;
//             }
//         }
//         Ok(())
//     }
// }
